DevCard_mvc/Models/Article.cs
namespace DevCard_mvc.Models
{
    public class Article
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }

        public Article(long id, string title, string image, string description)
        {
            Id = id;
            Title = title;
            Image = image;
            Description = description;
        }
    }

}

DevCard_mvc/Models/ErrorViewModel.cs
using System;

namespace DevCard_mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DevCard_mvc/Models/IndexModel.cs
using System.Collections.Generic;

namespace DevCard_mvc.Models
{
	public class IndexModel
	{
        public List<Project> Project { get; set; }
        public List<Article> Article { get; set; }

    }

}

DevCard_mvc/Models/Project.cs
using System;




namespace DevCard_mvc.Models
{
	public class Project
	{

		public long Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Client { get; set; }

        public Project(long id, string name ,string image, string description, string client)
        {
            Id = id;
            Name = name;
            Image=image;
            Description = description;
            Client = client;
        }
    }

}

DevCard_mvc/Controllers/HomeController.cs
using DevCard_mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace DevCard_mvc.Controllers
{
	public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact() {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DevCard_mvc/ViewComponents/ArticlesViewComponent.cs
using System.Collections.Generic;
using DevCard_mvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCard_mvc.ViewComponents
{
    public class ArticlesViewComponent:ViewComponent
    {

        public IViewComponentResult Invoke()
        {
            List<Article> articles = new List<Article>() {
            new Article(1,"Article1 " ,"blog-post-thumb-card-1.jpg", "About our hoem"),
            new Article(2 ,"Article2" ,"blog-post-thumb-card-2.jpg", "About our work in ofice"),
            new Article(3 , "Article 3","blog-post-thumb-card-3.jpg" , "About how to selse")

            };


            return View("_AArticless.cshtml" , articles );
        }

    }
}

DevCard_mvc/ViewComponents/ProjectsViewComponent.cs
using System.Collections.Generic;
using DevCard_mvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCard_mvc.ViewComponents
{
    public class ProjectsViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke(string name)
        {
            List<Project> projects = new List<Project>() {
            new Project(1,"تاکسی " ,"project-1.jpg" , "درخواست انلاین تاکس "  ," atria"),
            new Project(2,"زودفود ","project-2.jpg" , "درخواست انلاین غذا" , " snapfood"),
            new Project(3," مدارس","project-3.jpg" , "درخواست انلاین سرویس" , "monop "),
            new Project(4,"فضاپیما " ,"project-4.jpg", "درخواست انلاین فضاپیما" , "nasa")

            };

         
            return View("_PProjectss.cshtml" , projects);

        }

    }
}

DevCard_mvc/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<section class="cta-section theme-bg-light py-5">
	<div class="container text-center single-col-max-width">
		<h2 class="heading">ارتباط با ما</h2>
		<div class="intro">
			<p>
				شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
				نوشته و ارسال کنید.</a>
			</p>
			<p>از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
			<ul class="list-inline mb-0">
				<li class="list-inline-item mb-3">
					<a class="twitter" href="#">
						<i class="fab fa-twitter fa-fw fa-lg"></i>
					</a>
				</li>

				<li class="list-inline-item mb-3">
					<a class="linkedin" href="#">
						<i class="fab fa-linkedin-in fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="github" href="#">
						<i class="fab fa-github-alt fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="instagram" href="#">
						<i class="fab fa-instagram fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="stack-overflow" href="#">
						<i class="fab fa-stack-overflow fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="medium" href="#">
						<i class="fab fa-medium-m fa-fw fa-lg"></i>
					</a>
				</li>
				<li class="list-inline-item mb-3">
					<a class="codepen" href="#">
						<i class="fab fa-codepen fa-fw fa-lg"></i>
					</a>
				</li>
			</ul>
		</div>
</section>
<section class="contact-section px-3 py-5 p-md-5">
	<div class="container">
		<form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" action="#">
			<h3 class="text-center mb-3">در دسترس باشید!</h3>
			<div class="form-row">
				<div class="form-group col-md-6">
					<label class="sr-only" for="cname">نام</label>
					<input type="text" class="form-control" id="cname" name="name" placeholder="نام"
						   minlength="2" required="" aria-required="true">
				</div>
				<div class="form-group col-md-6">
					<label class="sr-only" for="cemail">ایمیل</label>
					<input type="email" class="form-control" id="cemail" name="email" placeholder="ایمیل"
						   required="" aria-required="true">
				</div>
				<div class="form-group col-12">
					<select id="services" class="custom-select" name="services">
						<option selected>سرویس مورد نظر خود را انتخاب کنید...</option>
						<option value="basic">نقره ای</option>
						<option value="standard">طلایی</option>
						<option value="premium">پلاتین</option>
						<option value="not sure">الماس</option>
					</select>
				</div>
				<div class="form-group col-12">
					<label class="sr-only" for="cmessage">پیغام شما</label>
					<textarea class="form-control" id="cmessage" name="message"
							  placeholder="پیغام خود را وارد نمایید ..." rows="10" required=""
							  aria-required="true"></textarea>
				</div>
				<div class="form-group col-12">
					<button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
				</div>
			</div>
		</form>
	</div>
</section>

DevCard_mvc/Views/Home/Index.cshtml
@model IndexModel

@{
    ViewData["Title"] = "Home Page";
}

<section class="about-me-section p-3 p-lg-5 theme-bg-light">
    <div class="container">
        <div class="profile-teaser media flex-column flex-lg-row">
            <img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="assets/images/me.jpeg" alt="">
            <div class="media-body">
                <h2 class="name font-weight-bold mb-1">حسین عباس آبادی</h2>
                <div class="tagline mb-3">برنامه نویس ارشد</div>
                <div class="bio mb-4">
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از
                    طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و
                    جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.</a>.
                </div>
                <div class="mb-4">
                    <a class="btn btn-primary mr-2 mb-3" href="http://www.atriya.com">
                        <i class="fas fa-arrow-alt-circle-right ml-2"></i><span class="d-none d-md-inline">
                            برو
                            به
                        </span> آتریا
                    </a>
                    <a class="btn btn-secondary mb-3" href="#">
                        <i class="fas fa-file-alt ml-2"></i>
                        <span class="d-none d-md-inline">مشاهده </span> نمونه کارها
                    </a>
                </div>
            </div>

        </div>
    </div>
</section>
@* partial view *@
@* <partial name="Project"> *@
   @*   @await Html.PartialAsync("Project"); *@
 @*    @await Html.PartialAsync("Project", new List<Project>()); *@
 
   @*   Component view *@
 @await Component.InvokeAsync("Projects" ,new {name="farid"}   );
    

    <div class="container">
        <hr>
    </div>



@await Component.InvokeAsync("Articles");

DevCard_mvc/Views/Home/_AArticless.cshtml
@model IEnumerable<DevCard_mvc.Models.Article>


    

    <section class="latest-blog-section p-3 p-lg-5">
        <div class="container">
            <h2 class="section-title font-weight-bold mb-5">آخرین مقالات</h2>
            <div class="row">

            @foreach (var article in Model)
            {

                <div class="col-md-4 mb-5">
                    <div class="card blog-post-card">
                        <img class="card-img-top" src="assets/images/blog/@article.Image" alt="image">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="theme-link" href="blog-post.html">
                                    @article.Title
                                </a>
                            </h5>
                            <p class="card-text">@article.Description
                              
                            </p>
                            <p class="mb-0"><a class="more-link" href="blog-post.html">ادامه مطلب</a></p>

                        </div>
                    </div>
                </div>


            }


            </div>
        </div>
    </section>

DevCard_mvc/Views/Home/_PProjectss.cshtml
@model IEnumerable<DevCard_mvc.Models.Project>
@* Or *@
@* @model List<Project>
 *@

<section class="featured-section p-3 p-lg-5">
	<div class="container">
		<h2 class="section-title font-weight-bold mb-5">خاص ترین پروژه ها</h2>
		<div class="row">

			@foreach (var Project in Model)
			{

				<div class="col-md-6 mb-5">
					<div class="card project-card">
						<div class="row no-gutters">
							<div class="col-lg-4 card-img-holder">
								<img src="assets/images/project/@Project.Image" class="card-img" alt="image">
							</div>
							<div class="col-lg-8">
								<div class="card-body">
									<h5 class="card-title">
										<a href="project.html" class="theme-link">
											@Project.Name
										</a>
									</h5>
									<p class="card-text">@Project.Description
									</p>
									<p class="card-text"><small class="text-muted"> مشتری : @Project.Client    </small></p>
								</div>
							</div>
						</div>
					</div>
				</div>

			}

		</div>
	</div>
</section>

DevCard_mvc/Views/Shared/Footer.cshtml
<footer class="footer text-center py-4">
	<small class="copyright">
		تولید شده توسط &copy; <a href="http://www.atriya.com" target="_blank">
			موسسه آموزشی
			آتریا
		</a>
	</small>
</footer>

DevCard_mvc/Views/Shared/Header.cshtml
<header class="header text-center">
	<div class="force-overflow">
		<h1 class="blog-name pt-lg-4 mb-0"><a href="index.html">حسین عباس آبادی</a></h1>

		<nav class="navbar navbar-expand-lg navbar-dark">

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
					aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column">
				<div class="profile-section pt-3 pt-lg-0">
					<img class="profile-image mb-3 rounded-circle mx-auto" src="assets/images/me.jpeg" alt="image">

					<div class="bio mb-3">
						سلام، حسین عباس آبادی هستم از موسسه آموزشی آتریا. به وبسایت شخصی من خوش
						آمدید.
					</div>
					<ul class="social-list list-inline py-2 mx-auto">
						<li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
						<li class="list-inline-item">
							<a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a>
						</li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
					</ul>
					<hr>
				</div>
				<ul class="navbar-nav flex-column text-right">
					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Index" , "Home")">
							<i class="fas fa-user fa-fw ml-2"></i>صفحه اصلی
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-controller="Home" , asp-action="Contact">
							<i class="fas fa-envelope-open-text fa-fw ml-2"></i>ارتباط با ما
						</a>
					</li>
				</ul>
			</div>
	</div>
	</nav>
	</div>
</header>

DevCard_mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">

<head>
	<title>DevCard از موسسه آتریا</title>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="shortcut icon" href="favicon.ico">

	<script defer src="~/assets/fontawesome/js/all.js"></script>
	<link  rel="stylesheet" href="~/assets/css/theme-1.css">
	<link  rel="stylesheet" href="~/assets/css/style.css">

</head>

<body>
	<partial  name="Header"    /  >
	

	<div class="main-wrapper">
		@RenderBody()
<partial  name="Footer" />

	</div>

	<!-- Javascript -->
	<script src="~/assets/plugins/jquery-3.4.1.min.js"></script>
	<script src="~/assets/plugins/popper.min.js"></script>
	<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

DevCard_mvc/Views/_Articles.cshtml
@model IEnumerable<DevCard_mvc.Models.Article>


    <section class="latest-blog-section p-3 p-lg-5">
        <div class="container">
            <h2 class="section-title font-weight-bold mb-5">آخرین مقالات</h2>
            <div class="row">

            @foreach (var article in Model)
            {

                <div class="col-md-4 mb-5">
                    <div class="card blog-post-card">
                        <img class="card-img-top" src="assets/images/blog/@article.Image" alt="image">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="theme-link" href="blog-post.html">
                                    @article.Title
                                </a>
                            </h5>
                            <p class="card-text">@article.Description
                              
                            </p>
                            <p class="mb-0"><a class="more-link" href="blog-post.html">ادامه مطلب</a></p>

                        </div>
                    </div>
                </div>


            }


            </div>
        </div>
    </section>